#!/usr/bin/env bash

set -e # exit when error

NAME='docsearch'
LICENSE="/*! ${NAME} ${VERSION:-UNRELEASED} | © Algolia | github.com/algolia/docsearch */"
DIST_DIR="../css"
DIST_FILE="$DIST_DIR/${NAME}.css"
DIST_FILE_MIN="$DIST_DIR/${NAME}.min.css"

mkdir -p "$DIST_DIR"

# ./dist/cdn/docsearch.css
echo "$LICENSE" > "$DIST_FILE";
./node_modules/.bin/node-sass --output-style expanded ./src/main.scss \
  | ./node_modules/.bin/postcss --use autoprefixer \
  >> "$DIST_FILE"

# ./dist/cdn/docsearch.min.css
./node_modules/.bin/postcss --use cssnano "$DIST_FILE" \
  >> "$DIST_FILE_MIN"

echo "=> $DIST_FILE_MIN compiled"
